// Project Team state — the people on a project (team members, each with an availability) and the assignment
// of members to the project's roles. Pure/deterministic: builders and helpers never read a clock or randomness
// and never mutate — every update returns a NEW model. (Member ids are generated by the server action, not
// here, so this stays deterministic.) It imports nothing from Planning / Occurrence / Execution / Delivery.

/** A team member's availability for the project. */
export type Availability = 'available' | 'tentative' | 'unavailable'

/** All availabilities, in canonical order. */
export const AVAILABILITIES: readonly Availability[] = ['available', 'tentative', 'unavailable']

/** Type guard: is `v` a valid availability? */
export function isAvailability(v: unknown): v is Availability {
  return typeof v === 'string' && (AVAILABILITIES as readonly string[]).includes(v)
}

/** One person on the project team. */
export interface TeamMember {
  id: string
  name: string
  availability: Availability
}

/** The persisted Project Team state: members + role→member assignments (roleId → memberId, or null/absent). */
export interface ProjectTeamState {
  members: TeamMember[]
  assignments: Record<string, string | null>
}

/** A fresh, empty team (no members, no assignments). */
export function emptyTeamState(): ProjectTeamState {
  return { members: [], assignments: {} }
}

/** Add a member (no-op if the id already exists) — returns a NEW state. */
export function addMember(state: ProjectTeamState, member: TeamMember): ProjectTeamState {
  if (state.members.some((m) => m.id === member.id)) return state
  return { ...state, members: [...state.members, member] }
}

/** Remove a member by id and clear any role assignment that referenced it — returns a NEW state. */
export function removeMember(state: ProjectTeamState, memberId: string): ProjectTeamState {
  const members = state.members.filter((m) => m.id !== memberId)
  const assignments: Record<string, string | null> = {}
  for (const [roleId, assigned] of Object.entries(state.assignments)) {
    assignments[roleId] = assigned === memberId ? null : assigned
  }
  return { members, assignments }
}

/** Set a member's availability — returns a NEW state (no-op if the member is unknown). */
export function setAvailability(state: ProjectTeamState, memberId: string, availability: Availability): ProjectTeamState {
  return { ...state, members: state.members.map((m) => (m.id === memberId ? { ...m, availability } : m)) }
}

/** Assign a member to a role, or clear the role's assignment when memberId is null — returns a NEW state. */
export function assignRole(state: ProjectTeamState, roleId: string, memberId: string | null): ProjectTeamState {
  return { ...state, assignments: { ...state.assignments, [roleId]: memberId } }
}

/** The member currently assigned to a role, or null. */
export function assignedMember(state: ProjectTeamState, roleId: string): TeamMember | null {
  const memberId = state.assignments[roleId] ?? null
  return memberId ? state.members.find((m) => m.id === memberId) ?? null : null
}
